title: "My Site"
description: "A crisp description for a crisp site."

# Enable plugins GitHub Pages allows
plugins:
  - jekyll-remote-theme

# MMistakes Basically Basic theme
remote_theme: "mmistakes/jekyll-theme-basically-basic"

# Optional but useful
markdown: kramdown
highlighter: rouge